
import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author ibrahim
 */
public class instractor extends javax.swing.JFrame {

    /**
     * Creates new form content
     */
    Connection conn = null;
    PreparedStatement pst = null;
        public  int Id=0;

    public instractor() throws ClassNotFoundException {

        initComponents();
        login log = new login();
        Id=Integer.parseInt(log.DBid);  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        open = new java.awt.Button();
        answerq = new java.awt.Label();
        announcement = new java.awt.TextField();
        submit = new java.awt.Button();
        feedback = new java.awt.Label();
        showfeedback = new java.awt.Button();
        Lasnswerq = new java.awt.TextField();
        an = new java.awt.Label();
        question = new java.awt.Label();
        showq = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        open.setActionCommand("open");
        open.setBackground(new java.awt.Color(0, 102, 153));
        open.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        open.setForeground(new java.awt.Color(255, 255, 255));
        open.setLabel("open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });

        answerq.setBackground(new java.awt.Color(0, 204, 204));
        answerq.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        answerq.setText("Answer the Quastions");

        announcement.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        announcement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                announcementActionPerformed(evt);
            }
        });

        submit.setActionCommand("submit");
        submit.setBackground(new java.awt.Color(0, 102, 153));
        submit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setLabel("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        feedback.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        feedback.setText("Feedback from Students");

        showfeedback.setActionCommand("show");
        showfeedback.setBackground(new java.awt.Color(0, 102, 153));
        showfeedback.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showfeedback.setForeground(new java.awt.Color(255, 255, 255));
        showfeedback.setLabel("Show");
        showfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showfeedbackActionPerformed(evt);
            }
        });

        Lasnswerq.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        an.setBackground(new java.awt.Color(0, 204, 204));
        an.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        an.setText("Write the announcement you wanna to share");

        question.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        question.setText("Quastions from Students");

        showq.setActionCommand("show");
        showq.setBackground(new java.awt.Color(0, 102, 153));
        showq.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showq.setForeground(new java.awt.Color(255, 255, 255));
        showq.setLabel("Show");
        showq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(an, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(open, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(announcement, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                                    .addComponent(Lasnswerq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(question, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                                    .addComponent(feedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showfeedback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(answerq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(an, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(announcement, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(answerq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lasnswerq, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(showq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(showfeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(open, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:

        try {

            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + "C:\\Users\\ibrahim\\Desktop\\[2020] OOP - Project Deliverables(1).pdf");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "check");
        }
    }//GEN-LAST:event_openActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        // TODO add your handling code here:
        /*   student st1 = new student();
         st1.setVisible(true);*/
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/courses", "root", "");
            String sql = "Insert into inst_review (inst_announcement,inst_answer_quastion,inst_id) values (?,?,?)";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, announcement.getText());
                pst.setString(2, Lasnswerq.getText());
                pst.setInt(3,Id );

                pst.execute();
                JOptionPane.showMessageDialog(null, "Data has been Saved");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_submitActionPerformed

    private void showfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showfeedbackActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/courses", "root", "");

            try {
                String sql = "select * from std_review";

                pst = conn.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {

                // int Id = rs.getInt("inst_id");

                //    int i =0;

                //    while (true){
                     //   if(i == Id){
                        String a = rs.getString("std_feedback");
                        feedback.setText(a);
                        break;
                     //   }
                    //    i++;
                   // }

                }

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_showfeedbackActionPerformed

    private void showqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showqActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:
 try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/courses", "root", "");
        

        try {
            String sql = "select * from std_review";

            pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                
            // int Id = rs.getInt("inst_id");
                
                    String a = rs.getString("std_quastion");
                    question.setText(a);
                

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }
 } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_showqActionPerformed

    private void announcementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_announcementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_announcementActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(content.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(content.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(content.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(content.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new instractor().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(instractor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Lasnswerq;
    private java.awt.Label an;
    private java.awt.TextField announcement;
    private java.awt.Label answerq;
    private java.awt.Label feedback;
    private java.awt.Button open;
    private java.awt.Label question;
    private java.awt.Button showfeedback;
    private java.awt.Button showq;
    private java.awt.Button submit;
    // End of variables declaration//GEN-END:variables
}
