
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleGroup = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();
        instCheck = new javax.swing.JCheckBox();
        stdCheck = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        userTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mailTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lnameTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Register");

        jLabel2.setText("Password");

        roleGroup.add(instCheck);
        instCheck.setText("instructor");

        roleGroup.add(stdCheck);
        stdCheck.setText("Student");

        jLabel3.setText("Role");

        jLabel1.setText("Username");

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("E-Mail");

        jLabel7.setText("last Name");

        jLabel6.setText("First Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(162, 162, 162)
                            .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(instCheck)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stdCheck)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2)))
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userTxt)
                            .addComponent(passTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(lnameTxt)
                            .addComponent(fnameTxt))))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instCheck)
                    .addComponent(stdCheck)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(registerBtn)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        try {
            String fname = fnameTxt.getText();
            String lname = lnameTxt.getText();
            String name = userTxt.getText();
            String pass = passTxt.getText();
            String mail = mailTxt.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/courses", "root", "");

            Statement st = con.createStatement();
            if (stdCheck.isSelected()) {
                String query = "SELECT * from student";
                ResultSet rs = st.executeQuery(query);
                boolean nameExist = false;
                boolean mailExist = false;

                while (rs.next()) {
                    String DBusername = rs.getString("std_username");
                    String DBusermail = rs.getString("std_email");
                    if (DBusername.equals(name)) {
                        nameExist = true;
                        break;
                    }
                    if (DBusermail.equals(mail)) {
                        mailExist = true;
                        break;
                    }
                }
                if (!nameExist && !mailExist) {
                    String state = "INSERT INTO `student`(`std_firstname`, `std_lastname` , `std_username`, `std_password`, `std_email`) VALUES ('" + fname + "','" + lname + "','" + name + "','" + pass + "','" + mail + "');";
                    st.executeUpdate(state);
                    JOptionPane.showMessageDialog(this, "Student Registered Successful", "Registerd", JOptionPane.INFORMATION_MESSAGE);
                    login loginFrame = new login();
                    loginFrame.setVisible(true);
                    this.setVisible(false);
                } else if (nameExist && !mailExist) {
                    JOptionPane.showMessageDialog(this, "User Already Exist");
                } else if (!nameExist && mailExist) {
                    JOptionPane.showMessageDialog(this, "Email Already Exist");
                }
            } else if (instCheck.isSelected()) {
                String query = "SELECT * from instructor";
                ResultSet rs = st.executeQuery(query);
                boolean nameExist = false;
                boolean mailExist = false;
                while (rs.next()) {
                    String DBusername = rs.getString("inst_username");
                    String DBusermail = rs.getString("inst_email");
                    if (DBusername.equals(name)) {
                        nameExist = true;
                        break;
                    }
                    if (DBusermail.equals(mail)) {
                        mailExist = true;
                        break;
                    }
                }
                if (!nameExist && !mailExist) {
                    String state = "INSERT INTO `instructor`(`inst_firstname`, `inst_lastname`, `inst_username`, `inst_password`,  `inst_email`) VALUES ('" + fname + "','" + lname + "','" + name + "','" + pass + "','" + mail + "');";
                    st.executeUpdate(state);
                    JOptionPane.showMessageDialog(this, "Instructor Registered Successful", "Registerd", JOptionPane.INFORMATION_MESSAGE);
                    login loginFrame = new login();
                    loginFrame.setVisible(true);
                    this.setVisible(false);
                } else if (nameExist && !mailExist) {
                    JOptionPane.showMessageDialog(this, "User Already Exist");
                } else if (!nameExist && mailExist) {
                    JOptionPane.showMessageDialog(this, "Email Already Exist");
                }

            }
        } catch (Exception e) {
            System.out.print(e.getLocalizedMessage());
            JOptionPane.showMessageDialog(this, "Error Connecting to Database", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JCheckBox instCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JButton registerBtn;
    private javax.swing.ButtonGroup roleGroup;
    private javax.swing.JCheckBox stdCheck;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
