
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zyade
 */
public class std_frame extends javax.swing.JFrame {
      public static String DB_id;

    /**
     * Creates new form display_image
     */
    public std_frame() {
        initComponents();
        savechangesbtn.setVisible(false);
        setSize(1100,620);
        setLocation(200,100);
        login log = new login();
        getData(log.DBid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        mailfld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passfld = new javax.swing.JPasswordField();
        Edit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Review = new javax.swing.JButton();
        savechangesbtn = new javax.swing.JButton();
        f_name = new javax.swing.JTextField();
        l_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        crsbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));

        jLabel1.setText("E-mail");

        jLabel2.setText("Name");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        passfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passfldActionPerformed(evt);
            }
        });

        Edit.setText("Edit my profile");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("Student's profile");

        Review.setText("Review");
        Review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewActionPerformed(evt);
            }
        });

        savechangesbtn.setText("Save changes");
        savechangesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savechangesbtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Last name");

        jLabel7.setText("First name");

        crsbtn.setText("courses");
        crsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crsbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Review)
                                .addComponent(crsbtn))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(savechangesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(f_name, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mailfld, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passfld, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(110, 110, 110)
                .addComponent(jLabel5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(f_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mailfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addComponent(passfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Review)
                            .addComponent(Edit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savechangesbtn)
                            .addComponent(crsbtn))))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passfldActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        ///username.setText(null);
     //   mailfld.setText(null);
       // passfld.setText(null);
       // f_name.setText(null);
       //  l_name.setText(null);
        
        savechangesbtn.setVisible(true);   
    }//GEN-LAST:event_EditActionPerformed

    private void ReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewActionPerformed
        try {
            // TODO add your handling code here:
            student std = new student();
            std.setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inst_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReviewActionPerformed

    private void savechangesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savechangesbtnActionPerformed
      
            // TODO add your handling code here:
          // Class.forName("com.mysql.jdbc.Driver");
           login lo = new login();
          get_Update(lo.DBid );
      
    
        
    }//GEN-LAST:event_savechangesbtnActionPerformed

    private void crsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crsbtnActionPerformed
        // TODO add your handling code here:
        courses_frame c=new courses_frame();
        c.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_crsbtnActionPerformed
  public void updatequery(String query)
  {
   Connection con=null;
   Statement st=null;
   try{ 
        con=DriverManager.getConnection("jdbc:mysql://localhost/courses", "root","");
        st=con.createStatement();
        st.executeUpdate(query);
       
        
        
   }catch(Exception ex)
   {
        JOptionPane.showMessageDialog(null, ex.getMessage());
   }
   
  }
    public class fun{
        Connection con=null;
        ResultSet rs=null;
        PreparedStatement ps=null;
        public ResultSet find(String s) throws SQLException
        {
            try{
           con=DriverManager.getConnection("jdbc:mysql://localhost/courses", "root","");
        //   ps=con.prepareStatement("SELECT `id` FROM student WHERE `std_username`='"+username.getText()+"'");
           //ps.setString(1, s);
          // rs=ps.executeQuery();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage()); 
            }
           
            return rs;
    }
    }
    void get_Update(String idDB){
        fun f=new fun();
        ResultSet rs=null;
       // String n="inst_username";
        //String pass="inst_password";
        //String email="inst_email";
        try {
            rs=f.find(idDB);
            int ID=Integer.parseInt(idDB);
           // System.out.print(ID);
           
            
            if (!username.getText().equals("")) {
            updatequery("UPDATE student SET`std_username`='" + username.getText() + "'WHERE `id`='"+ID+"'");
            
        }
        if (!f_name.getText().equals("")) {
            updatequery("UPDATE student SET`std_firstname`='" + f_name.getText() + "'WHERE `id`='"+ID+"'");
        }
        if (!l_name.getText().equals("")) {
            updatequery("UPDATE student SET`std_lastname`='" + l_name.getText() + "'WHERE `id`='"+ID+"'");
        }
        if (!passfld.getText().equals("")) {
            updatequery("UPDATE student SET`std_password`='" + passfld.getText() + "'WHERE `id`='"+ID+"'");
        }
        if (!mailfld.getText().equals("")) {
            updatequery("UPDATE student SET`std_email`='" + mailfld.getText() + "'WHERE `id`='"+ID+"'");
        }
        JOptionPane.showMessageDialog(this, "Data Has Been Edited");
    
        } catch (SQLException ex) {
            Logger.getLogger(inst_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    

    /**
     * @param args the command line arguments
     */
     public class function{
        Connection con=null;
        ResultSet rs=null;
        PreparedStatement ps=null;
        public ResultSet find(String s) throws SQLException
        {
            try{
           con=DriverManager.getConnection("jdbc:mysql://localhost/courses", "root","");
           ps=con.prepareStatement("Select *from student where id=?");
           ps.setString(1, s);
           rs=ps.executeQuery();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage()); 
            }
           
            return rs;
    }
    }
     void getData(String idDB){
         std_frame.function f=new std_frame.function();
        ResultSet rs=null;
        String n="std_username";
        String pass="std_password";
        String email="std_email";
        try {
            rs=f.find(idDB);
        } catch (SQLException ex) {
            Logger.getLogger(inst_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            if(rs.next())
            {
                username.setText(rs.getString("std_username"));
                mailfld.setText(rs.getString("std_email"));
                passfld.setText(rs.getString("std_password"));
                f_name.setText(rs.getString("std_firstname"));
                  l_name.setText(rs.getString("std_lastname"));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No data;");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
     }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(std_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(std_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(std_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(std_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new std_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JButton Review;
    private javax.swing.JButton crsbtn;
    private javax.swing.JTextField f_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField l_name;
    private javax.swing.JTextField mailfld;
    private javax.swing.JPasswordField passfld;
    private javax.swing.JButton savechangesbtn;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
