
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author ibrahim
 */
public class student extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public  int Id=0;
    Connection conn = null;
    PreparedStatement pst = null;

    public student() throws ClassNotFoundException {
        initComponents();
         login log = new login();
        Id=Integer.parseInt(log.DBid);  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        show = new java.awt.Button();
        lshow = new java.awt.Label();
        quastions = new java.awt.TextField();
        quastion = new java.awt.Label();
        answerq = new java.awt.Label();
        feedback = new java.awt.TextField();
        showasnwerqf = new java.awt.Button();
        lanswer = new java.awt.Label();
        submit_s = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        show.setActionCommand("show");
        show.setBackground(new java.awt.Color(0, 102, 153));
        show.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setLabel("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        lshow.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lshow.setText("The announcement from the instructor");

        quastions.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        quastion.setBackground(new java.awt.Color(0, 204, 204));
        quastion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        quastion.setText("Send Quastions");

        answerq.setBackground(new java.awt.Color(0, 204, 204));
        answerq.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        answerq.setText("Send Feedback");

        feedback.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        showasnwerqf.setActionCommand("show");
        showasnwerqf.setBackground(new java.awt.Color(0, 102, 153));
        showasnwerqf.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showasnwerqf.setForeground(new java.awt.Color(255, 255, 255));
        showasnwerqf.setLabel("Show");
        showasnwerqf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showasnwerqfActionPerformed(evt);
            }
        });

        lanswer.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lanswer.setText("Your Quastions' Answer ");

        submit_s.setActionCommand("submit");
        submit_s.setBackground(new java.awt.Color(0, 102, 153));
        submit_s.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submit_s.setForeground(new java.awt.Color(255, 255, 255));
        submit_s.setLabel("Submit");
        submit_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lshow, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showasnwerqf, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(quastion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(feedback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(answerq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(207, 207, 207))
                            .addComponent(quastions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(submit_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lshow, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(showasnwerqf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(quastion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quastions, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(answerq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(submit_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        show.getAccessibleContext().setAccessibleName("show");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/courses", "root", "");
            try {
                String sql = "select * from inst_review";

                pst = conn.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
       
                while (rs.next()) {


                    String a = rs.getString("inst_announcement");
                    lshow.setText(a);

                }

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_showActionPerformed

    private void showasnwerqfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showasnwerqfActionPerformed
        // TODO add your handling code here:
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/courses", "root", "");
            try {
                String sql = "select * from inst_review";

                pst = conn.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                
       
                
                while (rs.next()) {


                    String a = rs.getString("inst_answer_quastion");
                    lanswer.setText(a);

                }

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_showasnwerqfActionPerformed

    private void submit_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_sActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            /*   student st1 = new student();
         st1.setVisible(true);*/

            conn = DriverManager.getConnection("jdbc:mysql://localhost/courses", "root", "");
            String sql = "Insert into std_review (std_quastion,std_feedback,std_id) values (?,?,?)";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, quastions.getText());
                pst.setString(2, feedback.getText());
                 pst.setInt(3,Id );

                pst.execute();
                JOptionPane.showMessageDialog(null, "Data has been Saved");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }


    }//GEN-LAST:event_submit_sActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new student().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label answerq;
    public static java.awt.TextField feedback;
    private java.awt.Label lanswer;
    private java.awt.Label lshow;
    private java.awt.Label quastion;
    public static java.awt.TextField quastions;
    private java.awt.Button show;
    private java.awt.Button showasnwerqf;
    private java.awt.Button submit_s;
    // End of variables declaration//GEN-END:variables
}
